# Generated by Django 3.2.3 on 2021-06-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описания')),
                ('group', models.CharField(choices=[('assassin', 'assassin'), ('fighter', 'fighter'), ('support', 'support'), ('tank', 'tank'), ('magician', 'magician')], default='fighter', max_length=20, verbose_name='Группа')),
                ('img', models.ImageField(default='noimage.jpg', upload_to='heroes_image', verbose_name='Фото')),
            ],
        ),
    ]
