# Generated by Django 3.2.3 on 2021-06-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('tank', 'tank'), ('magician', 'magician'), ('assassin', 'assassin'), ('fighter', 'fighter'), ('support', 'support')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
