# Generated by Django 3.2.3 on 2021-06-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_heroes_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('support', 'support'), ('tank', 'tank'), ('fighter', 'fighter'), ('assassin', 'assassin'), ('magician', 'magician')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
