# Generated by Django 3.2.3 on 2021-06-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_heroes_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('tank', 'tank'), ('support', 'support'), ('magician', 'magician'), ('assassin', 'assassin'), ('fighter', 'fighter')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
