# Generated by Django 3.2.3 on 2021-06-03 05:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_heroes_group'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='heroes',
            managers=[
                ('odjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('fighter', 'fighter'), ('shooter', 'shooter'), ('tank', 'tank'), ('assassin', 'assassin'), ('magician', 'magician'), ('support', 'support')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
