# Generated by Django 3.2.3 on 2021-06-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210603_1155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('support', 'support'), ('fighter', 'fighter'), ('shooter', 'shooter'), ('magician', 'magician'), ('assassin', 'assassin'), ('tank', 'tank')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
