# Generated by Django 3.2.3 on 2021-06-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210603_1156'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='heroes',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('tank', 'tank'), ('fighter', 'fighter'), ('magician', 'magician'), ('support', 'support'), ('assassin', 'assassin'), ('shooter', 'shooter')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
