# Generated by Django 3.2.3 on 2021-06-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_heroes_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('assassin', 'assassin'), ('magician', 'magician'), ('fighter', 'fighter'), ('shooter', 'shooter'), ('support', 'support'), ('tank', 'tank')], default='fighter', max_length=20, verbose_name='Группа')),
            ],
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('assassin', 'assassin'), ('magician', 'magician'), ('fighter', 'fighter'), ('shooter', 'shooter'), ('support', 'support'), ('tank', 'tank')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
