# Generated by Django 3.2.3 on 2021-06-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210603_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('magician', 'magician'), ('support', 'support'), ('tank', 'tank'), ('fighter', 'fighter'), ('shooter', 'shooter'), ('assassin', 'assassin')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
