# Generated by Django 3.2.3 on 2021-06-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_heroes_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('assassin', 'assassin'), ('shooter', 'shooter'), ('tank', 'tank'), ('magician', 'magician'), ('fighter', 'fighter'), ('support', 'support')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
