# Generated by Django 3.2.3 on 2021-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_heroes_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='classs',
            field=models.CharField(default='Класс', max_length=255, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('tank', 'tank'), ('magician', 'magician'), ('fighter', 'fighter'), ('support', 'support'), ('shooter', 'shooter'), ('assassin', 'assassin')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Айди'),
        ),
    ]
