# Generated by Django 3.2.3 on 2021-06-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210604_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('fighter', 'Бойцы'), ('tank', 'tank'), ('support', 'support'), ('shooter', 'shooter'), ('assassin', 'assassin'), ('magician', 'Маги')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
