# Generated by Django 3.2.3 on 2021-06-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_heroes_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('support', 'support'), ('Маги', 'magician'), ('tank', 'tank'), ('shooter', 'shooter'), ('Ассасины', 'assassin'), ('Бойцы', 'fighter')], default='Бойцы', max_length=20, verbose_name='Группа'),
        ),
    ]
