# Generated by Django 3.2.3 on 2021-06-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_heroes_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('support', 'support'), ('magician', 'magician'), ('shooter', 'shooter'), ('fighter', 'fighter'), ('tank', 'tank'), ('assassin', 'assassin')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
