# Generated by Django 3.2.3 on 2021-06-11 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_heroes_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('tank', 'tank'), ('fighter', 'fighter'), ('shooter', 'shooter'), ('magician', 'magician'), ('support', 'support'), ('assassin', 'assassin')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='heroes_image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.heroes')),
            ],
        ),
    ]
