# Generated by Django 3.2.3 on 2021-06-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_heroes_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('shooter', 'shooter'), ('magician', 'magician'), ('assassin', 'assassin'), ('tank', 'tank'), ('fighter', 'fighter'), ('support', 'support')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
