# Generated by Django 3.2.3 on 2021-06-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_heroes_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='heroes_image')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('classs', models.CharField(default='Класс', max_length=255, verbose_name='Класс')),
                ('description', models.TextField(verbose_name='Описания')),
            ],
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('assassin', 'assassin'), ('fighter', 'fighter'), ('magician', 'magician'), ('support', 'support'), ('shooter', 'shooter'), ('tank', 'tank')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
