# Generated by Django 3.2.3 on 2021-06-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210611_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='classs',
            field=models.CharField(choices=[('phystt', 'phystt'), ('roum', 'roum'), ('magician', 'def')], default='roum', max_length=25, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('support', 'support'), ('shooter', 'shooter'), ('magician', 'magician'), ('tank', 'tank'), ('fighter', 'fighter'), ('assassin', 'assassin')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
