# Generated by Django 3.2.3 on 2021-06-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210611_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='classs',
            field=models.CharField(choices=[('magician', 'def'), ('roum', 'roum'), ('phystt', 'phystt')], default='roum', max_length=25, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('support', 'support'), ('tank', 'tank'), ('fighter', 'fighter'), ('magician', 'magician'), ('shooter', 'shooter'), ('assassin', 'assassin')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
