# Generated by Django 3.2.3 on 2021-06-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210611_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroesClass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описания')),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='classs',
            field=models.CharField(choices=[('roum', 'roum'), ('magician', 'def'), ('phystt', 'phystt')], default='roum', max_length=25, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('shooter', 'shooter'), ('assassin', 'assassin'), ('tank', 'tank'), ('support', 'support'), ('magician', 'magician'), ('fighter', 'fighter')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
