# Generated by Django 3.2.3 on 2021-06-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210612_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('fighter', 'fighter'), ('tank', 'tank'), ('shooter', 'shooter'), ('support', 'support'), ('assassin', 'assassin'), ('magician', 'magician')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='heroesclass',
            name='name',
            field=models.CharField(choices=[('fighter', 'fighter'), ('tank', 'tank'), ('shooter', 'shooter'), ('support', 'support'), ('assassin', 'assassin'), ('magician', 'magician')], max_length=255, verbose_name='Имя'),
        ),
    ]
