# Generated by Django 3.2.3 on 2021-06-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210612_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroesClass',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='classs',
            field=models.CharField(choices=[('roum', 'roum'), ('phystt', 'phystt'), ('magician', 'def')], default='roum', max_length=25, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('tank', 'tank'), ('support', 'support'), ('magician', 'magician'), ('assassin', 'assassin'), ('fighter', 'fighter'), ('shooter', 'shooter')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
