# Generated by Django 3.2.3 on 2021-06-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210612_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='classs',
        ),
        migrations.AddField(
            model_name='equipment',
            name='group',
            field=models.CharField(choices=[('deff', 'deff'), ('physatt', 'physatt'), ('magatt', 'magatt')], default=None, max_length=25, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('tank', 'tank'), ('shooter', 'shooter'), ('fighter', 'fighter'), ('support', 'support'), ('magician', 'magician'), ('assassin', 'assassin')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
