# Generated by Django 3.2.3 on 2021-06-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_heroes_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='group',
            field=models.CharField(choices=[('deff', 'deff'), ('magatt', 'magatt'), ('physatt', 'physatt')], default='magatt', max_length=25, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('shooter', 'shooter'), ('assassin', 'assassin'), ('support', 'support'), ('tank', 'tank'), ('fighter', 'fighter'), ('magician', 'magician')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
