# Generated by Django 3.2.3 on 2021-06-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210612_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='group',
            field=models.CharField(choices=[('physatt', 'physatt'), ('magatt', 'magatt'), ('deff', 'deff')], default='magatt', max_length=25, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('shooter', 'shooter'), ('magician', 'magician'), ('tank', 'tank'), ('support', 'support'), ('assassin', 'assassin'), ('fighter', 'fighter')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
