# Generated by Django 3.2.3 on 2021-06-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20210612_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='classs',
            field=models.CharField(choices=[('magatt', 'magatt'), ('deff', 'deff'), ('physatt', 'physatt')], default='magatt', max_length=25, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('support', 'support'), ('tank', 'tank'), ('shooter', 'shooter'), ('assassin', 'assassin'), ('magician', 'magician'), ('fighter', 'fighter')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
