# Generated by Django 3.2.3 on 2021-06-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20210612_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='classs',
            field=models.CharField(choices=[('deff', 'deff'), ('physatt', 'physatt'), ('magatt', 'magatt')], default='magatt', max_length=25, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('support', 'support'), ('magician', 'magician'), ('shooter', 'shooter'), ('tank', 'tank'), ('fighter', 'fighter'), ('assassin', 'assassin')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
