# Generated by Django 3.2.3 on 2021-06-14 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20210612_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='classs',
            field=models.CharField(choices=[('physatt', 'physatt'), ('deff', 'deff'), ('magatt', 'magatt')], default='magatt', max_length=25, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('shooter', 'shooter'), ('tank', 'tank'), ('fighter', 'fighter'), ('support', 'support'), ('assassin', 'assassin'), ('magician', 'magician')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(verbose_name='ХП')),
                ('hp_regen', models.IntegerField(verbose_name='ХП реген')),
                ('mp', models.IntegerField(verbose_name='МП')),
                ('mana_regen', models.IntegerField(verbose_name='Мага реген')),
                ('phyatt', models.IntegerField(verbose_name='Физическая атака')),
                ('phydef', models.IntegerField(verbose_name='Физическая защита')),
                ('magatt', models.IntegerField(verbose_name='Магическая атака')),
                ('magdef', models.IntegerField(verbose_name='Магическая защита')),
                ('mov_speed', models.IntegerField(verbose_name='Скорость передвижение')),
                ('att_speed', models.IntegerField(verbose_name='Скорость атаки')),
                ('phy_vam', models.IntegerField(verbose_name='Физический вампиризм')),
                ('mag_vam', models.IntegerField(verbose_name='Магический вампиризм')),
                ('bas_atk_crit', models.IntegerField(verbose_name='Базовая вероятность критического удара')),
                ('ability_crit', models.IntegerField(verbose_name='Вероятность критического удара способностей')),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.heroes', verbose_name='Имя')),
            ],
        ),
    ]
