# Generated by Django 3.2.3 on 2021-06-17 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20210615_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='classs',
            field=models.CharField(choices=[('physatt', 'physatt'), ('magatt', 'magatt'), ('deff', 'deff')], default='magatt', max_length=25, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('tank', 'tank'), ('shooter', 'shooter'), ('support', 'support'), ('assassin', 'assassin'), ('fighter', 'fighter'), ('magician', 'magician')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Айди')),
                ('description', models.TextField(verbose_name='Описания')),
                ('img', models.ImageField(default='noimage.jpg', upload_to='heroes_image', verbose_name='Фото')),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.heroes', verbose_name='Имя')),
            ],
        ),
    ]
