# Generated by Django 3.2.3 on 2021-06-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_auto_20210625_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='classs',
            field=models.CharField(choices=[('physatt', 'physatt'), ('magatt', 'magatt'), ('deff', 'deff')], default='magatt', max_length=25, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('tank', 'tank'), ('fighter', 'fighter'), ('assassin', 'assassin'), ('magician', 'magician'), ('support', 'support'), ('shooter', 'shooter')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
