# Generated by Django 3.2.3 on 2021-06-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20210625_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('tank', 'tank'), ('shooter', 'shooter'), ('fighter', 'fighter'), ('magician', 'magician'), ('assassin', 'assassin'), ('support', 'support')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
