# Generated by Django 3.2.3 on 2021-06-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20210625_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('fighter', 'fighter'), ('shooter', 'shooter'), ('support', 'support'), ('assassin', 'assassin'), ('magician', 'magician'), ('tank', 'tank')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
