# Generated by Django 3.2.3 on 2021-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20210628_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='classs',
            field=models.CharField(choices=[('deff', 'deff'), ('physatt', 'physatt'), ('magatt', 'magatt')], default='magatt', max_length=25, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('magician', 'magician'), ('tank', 'tank'), ('support', 'support'), ('assassin', 'assassin'), ('shooter', 'shooter'), ('fighter', 'fighter')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
