# Generated by Django 3.2.3 on 2021-06-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20210628_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='classs',
            field=models.CharField(choices=[('physatt', 'physatt'), ('magatt', 'magatt'), ('deff', 'deff')], default='magatt', max_length=25, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='group',
            field=models.CharField(choices=[('magician', 'magician'), ('shooter', 'shooter'), ('fighter', 'fighter'), ('assassin', 'assassin'), ('tank', 'tank'), ('support', 'support')], default='fighter', max_length=20, verbose_name='Группа'),
        ),
    ]
